// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAMzPo1J1DypqnvKON7qCXIzvX5cO0mlI',
    appId: '1:978533022478:web:ca9327b608c40c167ff55f',
    messagingSenderId: '978533022478',
    projectId: 'mathlingo-90084',
    authDomain: 'mathlingo-90084.firebaseapp.com',
    storageBucket: 'mathlingo-90084.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUDk5xtsD5FG6fKxKSVNbmgOBhLhSPL_0',
    appId: '1:978533022478:android:bc5fc6aa979153a87ff55f',
    messagingSenderId: '978533022478',
    projectId: 'mathlingo-90084',
    storageBucket: 'mathlingo-90084.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvJKkM9znbSG0oVlYYDobhAvubW5qb_lk',
    appId: '1:978533022478:ios:72e41a9b3ac808dc7ff55f',
    messagingSenderId: '978533022478',
    projectId: 'mathlingo-90084',
    storageBucket: 'mathlingo-90084.firebasestorage.app',
    iosBundleId: 'com.mathlingo.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvJKkM9znbSG0oVlYYDobhAvubW5qb_lk',
    appId: '1:978533022478:ios:7aeb0b5d3d7ccd0e7ff55f',
    messagingSenderId: '978533022478',
    projectId: 'mathlingo-90084',
    storageBucket: 'mathlingo-90084.firebasestorage.app',
    iosBundleId: 'com.example.mathlingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAMzPo1J1DypqnvKON7qCXIzvX5cO0mlI',
    appId: '1:978533022478:web:b922d5b64afee0b27ff55f',
    messagingSenderId: '978533022478',
    projectId: 'mathlingo-90084',
    authDomain: 'mathlingo-90084.firebaseapp.com',
    storageBucket: 'mathlingo-90084.firebasestorage.app',
  );
}
